server:
  port: 8080
  servlet:
    context-path: /mj
logging:
  level:
    ROOT: info
    com.github.starrygaze.midjourney: debug
knife4j:
  enable: true
  openapi:
    title: Midjourney Proxy API文档
    description: 代理 MidJourney 的discord频道，实现api形式调用AI绘图,公益
    concat: starrygaze
    url: https://github.com/Starry-Gaze/MidJourneyAidProxy
    version: v0.0.1
    terms-of-service-url: https://github.com/Starry-Gaze/MidJourneyAidProxy
    group:
      api:
        group-name: API
        api-rule: package
        api-rule-resources:
          - com.github.starrygaze.midjourney.controller
mj:
  #任务存储
  task-store:
    type: ${TASK_STORE_TYPE}
    timeout: 30d
  #discord配置
  discord:
    #服务器id
    guild-id: ${GUILD_ID}
    #频道id
    channel-id: ${CHANNEL_ID}
    #登录token
    user-token: ${USER_TOKEN}
    #机器人token
    bot-token: ${BOT_TOKEN}
  #翻译方式
  translate-way: ${TANSLATE_WAY}
  #任务队列配置
  queue:
    #任务超时时间(分钟)
    timeout-minutes: 5
    #并发数
    core-size: 3
    #等待队列长度
    queue-size: 10
  #百度翻译配置
  baidu-translate:
    #百度翻译的APP_ID
    appid: ${APPID}
    #百度翻译的密钥
    app-secret: ${APP_SECRECT}
  #openai配置
  openai:
    #gpt的api-key
    gpt-api-key: ${GPT_API_KEY}
    #使用的模型
    model: "gpt-3.5-turbo"
    #返回结果的最大分词数
    max-tokens: 2048
    #相似度，取值 0-2
    temperature: 0
    #任务状态变更回调地址(你实际中转的项目地址)
  notify-hook: ${NOTIFY_HOOK}

spring:
  cache:
    type: ${SPRING_CACHE_TYPE}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PW}